name: Azure CDN CI/CD

on:
  push:
    branches: [ "release" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Run node/CLI
      run: |
        npm install
        npm run build --if-present
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - uses: azure/CLI@v1
      with:
        inlineScript: |
          az storage blob delete-batch --account-name bmeyerpublic --auth-mode key -s icons 
          az storage blob upload-batch --account-name bmeyerpublic --auth-mode key -d icons -s dist
          az cdn endpoint purge --content-paths  "/*" --profile-name "bmeyerpublic" --name "icons-bmeyer" --resource-group "webapps"
    - name: Run azure/logut
      run: az logout
      if: always()
